*DECK DDRES1
      SUBROUTINE DDRES1 (T, Y, YPRIME, DELTA, IRES, RPAR, IPAR)
C***BEGIN PROLOGUE  DDRES1
C***SUBSIDIARY
C***PURPOSE  First residual evaluator for DDASQC.
C***LIBRARY   SLATEC (DASSL)
C***TYPE      DOUBLE PRECISION (SDRES1-S, DDRES1-D)
C***AUTHOR  PETZOLD, LINDA R., (LLNL)
C***SEE ALSO  DDASQC
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   891013  DATE WRITTEN
C   901001  Converted prologue to 4.0 format and made all argument
C           declarations explicit.  (FNF)
C***END PROLOGUE  DDRES1
      INTEGER  IRES, IPAR(*)
      DOUBLE PRECISION  T, Y(*), YPRIME(*), DELTA(*), RPAR(*)
C***FIRST EXECUTABLE STATEMENT  DDRES1
      DELTA(1) = YPRIME(1) + 10.0D0*Y(1)
      DELTA(2) = Y(2) + Y(1) - 1.0D0
      RETURN
      END
