*DECK DF0C
      DOUBLE PRECISION FUNCTION DF0C (X)
C***BEGIN PROLOGUE  DF0C
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF0C
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF0C
      DF0C = 1.D0/(X*X+1.D-4)
      RETURN
      END
