*DECK DF0O
      DOUBLE PRECISION FUNCTION DF0O (X)
C***BEGIN PROLOGUE  DF0O
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF0O
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF0O
      DF0O = (0.2D+01*SIN(X))**14
      RETURN
      END
