*DECK DF0S
      DOUBLE PRECISION FUNCTION DF0S (X)
C***BEGIN PROLOGUE  DF0S
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF0S
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF0S
      DF0S = 0.0D+00
      IF(X.NE.0.0D+00) DF0S = 0.1D+01/SQRT(X)
      RETURN
      END
