!DECK DF0WS
REAL(8) FUNCTION DF0WS(X)
  IMPLICIT NONE
  !***BEGIN PROLOGUE  DF0WS
  !***PURPOSE  Subsidiary to
  !***LIBRARY   SLATEC
  !***AUTHOR  (UNKNOWN)
  !***ROUTINES CALLED  (NONE)
  !***REVISION HISTORY  (YYMMDD)
  !   ??????  DATE WRITTEN
  !   891214  Prologue converted to Version 4.0 format.  (BAB)
  !***END PROLOGUE  DF0WS
  REAL(8) :: X
  !***FIRST EXECUTABLE STATEMENT  DF0WS
  DF0WS = SIN(0.1D+02*X)
END FUNCTION DF0WS
