*DECK DF0WS
      DOUBLE PRECISION FUNCTION DF0WS (X)
C***BEGIN PROLOGUE  DF0WS
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF0WS
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF0WS
      DF0WS  = SIN(0.1D+02*X)
      RETURN
      END
