*DECK DF1C
      DOUBLE PRECISION FUNCTION DF1C (X)
C***BEGIN PROLOGUE  DF1C
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF1C
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF1C
      DF1C = 0.0D+00
      IF(X.NE.0.33D+00) DF1C = (X-0.5D+00)*ABS(X-0.33D+00)**(-0.9D+00)
      RETURN
      END
