*DECK DF1G
      DOUBLE PRECISION FUNCTION DF1G (X)
C***BEGIN PROLOGUE  DF1G
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF1G
      DOUBLE PRECISION PI,X
      DATA PI /3.1415926535897932D0/
C***FIRST EXECUTABLE STATEMENT  DF1G
      DF1G = 2.0D0/(2.0D0+SIN(10.0D0*PI*X))
      RETURN
      END
