*DECK DF1O
      DOUBLE PRECISION FUNCTION DF1O (X)
C***BEGIN PROLOGUE  DF1O
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF1O
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF1O
      DF1O = 0.1D+01
      IF(X.GT.0.31415926535897932D+01) DF1O = 0.0D+00
      RETURN
      END
