!*==DF1S.f90  processed by SPAG 6.72Dc at 10:52 on  6 Feb 2019
!DECK DF1S
      DOUBLE PRECISION FUNCTION DF1S(X)
      IMPLICIT NONE
!*--DF1S5
!***BEGIN PROLOGUE  DF1S
!***PURPOSE  Subsidiary to
!***LIBRARY   SLATEC
!***AUTHOR  (UNKNOWN)
!***ROUTINES CALLED  (NONE)
!***REVISION HISTORY  (YYMMDD)
!   ??????  DATE WRITTEN
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!***END PROLOGUE  DF1S
      DOUBLE PRECISION X
!***FIRST EXECUTABLE STATEMENT  DF1S
      DF1S = 0.2D+01/(0.2D+01+SIN(0.314159D+02*X))
      END FUNCTION DF1S
