!DECK DF1S
REAL(8) FUNCTION DF1S(X)
  IMPLICIT NONE
  !***BEGIN PROLOGUE  DF1S
  !***PURPOSE  Subsidiary to
  !***LIBRARY   SLATEC
  !***AUTHOR  (UNKNOWN)
  !***ROUTINES CALLED  (NONE)
  !***REVISION HISTORY  (YYMMDD)
  !   ??????  DATE WRITTEN
  !   891214  Prologue converted to Version 4.0 format.  (BAB)
  !***END PROLOGUE  DF1S
  REAL(8) :: X
  !***FIRST EXECUTABLE STATEMENT  DF1S
  DF1S = 0.2D+01/(0.2D+01+SIN(0.314159D+02*X))
END FUNCTION DF1S
