*DECK DF2G
      DOUBLE PRECISION FUNCTION DF2G (X)
C***BEGIN PROLOGUE  DF2G
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF2G
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF2G
      DF2G = X*SIN(0.3D+02*X)*COS(0.5D+02*X)
      RETURN
      END
