*DECK DF2N
      DOUBLE PRECISION FUNCTION DF2N (X)
C***BEGIN PROLOGUE  DF2N
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF2N
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF2N
      DF2N=X**(-0.9D+00)
      RETURN
      END
