!*==DF2P.f90  processed by SPAG 6.72Dc at 10:52 on  6 Feb 2019
!DECK DF2P
REAL(8) FUNCTION DF2P(X)
  IMPLICIT NONE
  !*--DF2P5
  !***BEGIN PROLOGUE  DF2P
  !***PURPOSE  Subsidiary to
  !***LIBRARY   SLATEC
  !***AUTHOR  (UNKNOWN)
  !***ROUTINES CALLED  (NONE)
  !***REVISION HISTORY  (YYMMDD)
  !   ??????  DATE WRITTEN
  !   891214  Prologue converted to Version 4.0 format.  (BAB)
  !***END PROLOGUE  DF2P
  REAL(8) :: X
  !***FIRST EXECUTABLE STATEMENT  DF2P
  DF2P = SIN(0.314159D+03*X)/(0.314159D+01*X)
END FUNCTION DF2P
