*DECK DF2P
      DOUBLE PRECISION FUNCTION DF2P (X)
C***BEGIN PROLOGUE  DF2P
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF2P
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF2P
      DF2P = SIN(0.314159D+03*X)/(0.314159D+01*X)
      RETURN
      END
