*DECK DF2S
      DOUBLE PRECISION FUNCTION DF2S (X)
C***BEGIN PROLOGUE  DF2S
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF2S
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF2S
      DF2S = 0.1D+03
      IF(X.NE.0.0D+00) DF2S = SIN(0.314159D+03*X)/(0.314159D+01*X)
      RETURN
      END
