!DECK DF3G
REAL(8) FUNCTION DF3G(X)
  IMPLICIT NONE
  !***BEGIN PROLOGUE  DF3G
  !***PURPOSE  Subsidiary to
  !***LIBRARY   SLATEC
  !***AUTHOR  (UNKNOWN)
  !***ROUTINES CALLED  (NONE)
  !***REVISION HISTORY  (YYMMDD)
  !   ??????  DATE WRITTEN
  !   891214  Prologue converted to Version 4.0 format.  (BAB)
  !***END PROLOGUE  DF3G
  REAL(8) :: X
  !***FIRST EXECUTABLE STATEMENT  DF3G
  DF3G = ABS(X-0.33D+00)**(-.90D+00)
END FUNCTION DF3G
