!DECK DF3S
REAL(8) FUNCTION DF3S(X)
  IMPLICIT NONE
  !***BEGIN PROLOGUE  DF3S
  !***PURPOSE  Subsidiary to
  !***LIBRARY   SLATEC
  !***AUTHOR  (UNKNOWN)
  !***ROUTINES CALLED  (NONE)
  !***REVISION HISTORY  (YYMMDD)
  !   ??????  DATE WRITTEN
  !   891214  Prologue converted to Version 4.0 format.  (BAB)
  !***END PROLOGUE  DF3S
  REAL(8) :: X
  !***FIRST EXECUTABLE STATEMENT  DF3S
  DF3S = 0.1D+01
  IF ( X>0.31415926535897932D+01 ) DF3S = 0.0D+00
END FUNCTION DF3S
