*DECK DF4P
      DOUBLE PRECISION FUNCTION DF4P (X)
C***BEGIN PROLOGUE  DF4P
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF4P
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF4P
      DF4P = 0.0D+00
      IF(X.GT.0.0D+00) DF4P = 0.1D+01/(X*SQRT(X))
      RETURN
      END
