*DECK DF4S
      DOUBLE PRECISION FUNCTION DF4S (X)
C***BEGIN PROLOGUE  DF4S
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF4S
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF4S
      DF4S = 0.00D+00
      IF(X-0.33D+00 .NE. 0.00D+00) DF4S=ABS(X-0.33D+00)**(-0.999D+00)
      RETURN
      END
