*DECK DF5S
      DOUBLE PRECISION FUNCTION DF5S (X)
C***BEGIN PROLOGUE  DF5S
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DF5S
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DF5S
      DF5S = 0.0D+00
      IF(X.NE.0.0D+00) DF5S = 1.0D+00/(X*SQRT(X))
      RETURN
      END
