*DECK DFB
      DOUBLE PRECISION FUNCTION DFB (X)
C***BEGIN PROLOGUE  DFB
C***PURPOSE  Subsidiary to DBSPCK.
C***LIBRARY   SLATEC
C***TYPE      DOUBLE PRECISION (FB-S, DFB-D)
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C   930214  Added TYPE statement.  (WRB)
C***END PROLOGUE  DFB
      DOUBLE PRECISION X
C***FIRST EXECUTABLE STATEMENT  DFB
      DFB = 1.0D0
      RETURN
      END
