!*==DFB.f90  processed by SPAG 6.72Dc at 10:52 on  6 Feb 2019
!DECK DFB
DOUBLE PRECISION FUNCTION DFB(X)
  IMPLICIT NONE
  !*--DFB5
  !***BEGIN PROLOGUE  DFB
  !***PURPOSE  Subsidiary to DBSPCK.
  !***LIBRARY   SLATEC
  !***TYPE      DOUBLE PRECISION (FB-S, DFB-D)
  !***AUTHOR  (UNKNOWN)
  !***ROUTINES CALLED  (NONE)
  !***REVISION HISTORY  (YYMMDD)
  !   ??????  DATE WRITTEN
  !   891214  Prologue converted to Version 4.0 format.  (BAB)
  !   930214  Added TYPE statement.  (WRB)
  !***END PROLOGUE  DFB
  DOUBLE PRECISION X
  !***FIRST EXECUTABLE STATEMENT  DFB
  DFB = 1.0D0
END FUNCTION DFB
