*DECK DFQD1
      DOUBLE PRECISION FUNCTION DFQD1 (X)
C***BEGIN PROLOGUE  DFQD1
C***SUBSIDIARY
C***PURPOSE  Function evaluator for DQNC79 and DGAUS8 quick checks.
C***LIBRARY   SLATEC
C***TYPE      DOUBLE PRECISION (FQD1-S, DFQD1-D)
C***AUTHOR  Boland, W. Robert, (LANL)
C***SEE ALSO  DQG8TS, DQN79Q
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   920229  DATE WRITTEN
C***END PROLOGUE  DFQD1
C     .. Scalar Arguments ..
      DOUBLE PRECISION X
C     .. Intrinsic Functions ..
      INTRINSIC SQRT
C***FIRST EXECUTABLE STATEMENT  DFQD1
      DFQD1 = 0.0D0
      IF (X .GT. 0.0D0) THEN
        DFQD1 = 1.0D0/SQRT(X)
      ENDIF
      RETURN
      END
