*DECK DFQD2
      DOUBLE PRECISION FUNCTION DFQD2 (X)
C***BEGIN PROLOGUE  DFQD2
C***SUBSIDIARY
C***PURPOSE  Function evaluator for DQNC79 and DGAUS8 quick checks.
C***LIBRARY   SLATEC
C***TYPE      DOUBLE PRECISION (FQD2-S, DFQD2-D)
C***AUTHOR  Boland, W. Robert, (LANL)
C***SEE ALSO  DQG8TS, DQN79Q
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   920229  DATE WRITTEN
C***END PROLOGUE  DFQD2
C     .. Scalar Arguments ..
      DOUBLE PRECISION X
C     .. Intrinsic Functions ..
      INTRINSIC COS,EXP
C***FIRST EXECUTABLE STATEMENT  DFQD2
      DFQD2 = EXP(X)*COS(10.0D0*X)
      RETURN
      END
