*DECK DQJAC2
      SUBROUTINE DQJAC2 (N, X, FVEC, FJAC, LDFJAC, IFLAG)
C***BEGIN PROLOGUE  DQJAC2
C***PURPOSE
C***LIBRARY   SLATEC
C***KEYWORDS  QUICK CHECK
C***AUTHOR  (UNKNOWN)
C***DESCRIPTION
C
C     SUBROUTINE TO EVALUATE THE FULL JACOBIAN FOR TEST PROBLEM USED
C     IN QUICK CHECK OF DNSQE.
C
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   890831  Modified array declarations.  (WRB)
C   890831  REVISION DATE from Version 3.2
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DQJAC2
      INTEGER IFLAG, LDFJAC, N
      DOUBLE PRECISION FJAC(LDFJAC,*), FVEC(*), X(*)
C***FIRST EXECUTABLE STATEMENT  DQJAC2
      FJAC(1,1) = -1.0D0
      FJAC(1,2) = 0.0D0
      FJAC(2,1) = -2.0D1*X(1)
      FJAC(2,2) = 1.0D1
      RETURN
      END
