*DECK DT3
      DOUBLE PRECISION FUNCTION DT3 (X)
C***BEGIN PROLOGUE  DT3
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  DF3S
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DT3
      DOUBLE PRECISION A,B,DF3S,X,X1,Y
C***FIRST EXECUTABLE STATEMENT  DT3
      A = 0.0D+00
      B = 0.5D+01
      X1 = X+0.1D+01
      Y = (B-A)/X1+A
      DT3 = (B-A)*DF3S(Y)/X1/X1
      RETURN
      END
