*DECK F0C
      REAL FUNCTION F0C (X)
C***BEGIN PROLOGUE  F0C
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F0C
      REAL X
C***FIRST EXECUTABLE STATEMENT  F0C
      F0C = 1.E0/(X*X+1.E-4)
      RETURN
      END
