*DECK F0O
      REAL FUNCTION F0O (X)
C***BEGIN PROLOGUE  F0O
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F0O
      REAL X
C***FIRST EXECUTABLE STATEMENT  F0O
      F0O = (2.0E0*SIN(X))**14
      RETURN
      END
