!DECK F0O
REAL FUNCTION F0O(X)
  IMPLICIT NONE
  !***BEGIN PROLOGUE  F0O
  !***PURPOSE  Subsidiary to
  !***LIBRARY   SLATEC
  !***AUTHOR  (UNKNOWN)
  !***ROUTINES CALLED  (NONE)
  !***REVISION HISTORY  (YYMMDD)
  !   ??????  DATE WRITTEN
  !   891214  Prologue converted to Version 4.0 format.  (BAB)
  !***END PROLOGUE  F0O
  REAL X
  !***FIRST EXECUTABLE STATEMENT  F0O
  F0O = (2.0E0*SIN(X))**14
END FUNCTION F0O
