*DECK F0WS
      REAL FUNCTION F0WS (X)
C***BEGIN PROLOGUE  F0WS
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F0WS
      REAL X
C***FIRST EXECUTABLE STATEMENT  F0WS
      F0WS  = SIN(10.0*X)
      RETURN
      END
