*DECK F1G
      REAL FUNCTION F1G (X)
C***BEGIN PROLOGUE  F1G
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F1G
      REAL PI,X
      DATA PI/3.1415926535897932/
C***FIRST EXECUTABLE STATEMENT  F1G
      F1G = 2.0/(2.0+SIN(10.0*PI*X))
      RETURN
      END
