*DECK F1N
      REAL FUNCTION F1N (X)
C***BEGIN PROLOGUE  F1N
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F1N
      REAL X
C***FIRST EXECUTABLE STATEMENT  F1N
      F1N=1.0E0/(X**4+X**2+1.0E0)
      RETURN
      END
