*DECK F1S
      REAL FUNCTION F1S (X)
C***BEGIN PROLOGUE  F1S
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F1S
      REAL X
C***FIRST EXECUTABLE STATEMENT  F1S
      F1S = 0.2E+01/(0.2E+01+SIN(0.314159E+02*X))
      RETURN
      END
