*DECK F1WS
      REAL FUNCTION F1WS (X)
C***BEGIN PROLOGUE  F1WS
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F1WS
      REAL X
C***FIRST EXECUTABLE STATEMENT  F1WS
      F1WS = ABS(X-0.33E+00)**(-0.999E+00)
      RETURN
      END
