*DECK F2G
      REAL FUNCTION F2G (X)
C***BEGIN PROLOGUE  F2G
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F2G
      REAL X
C***FIRST EXECUTABLE STATEMENT  F2G
      F2G = X*SIN(0.3E+02*X)*COS(0.5E+02*X)
      RETURN
      END
