*DECK F2N
      REAL FUNCTION F2N (X)
C***BEGIN PROLOGUE  F2N
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F2N
      REAL X
C***FIRST EXECUTABLE STATEMENT  F2N
      F2N=X**(-0.9E+00)
      RETURN
      END
