*DECK F2S
      REAL FUNCTION F2S (X)
C***BEGIN PROLOGUE  F2S
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F2S
      REAL X
C***FIRST EXECUTABLE STATEMENT  F2S
      F2S = 100.0
      IF(X.NE.0.0) F2S = SIN(0.314159E+03*X)/(0.314159E+01*X)
      RETURN
      END
