*DECK F3G
      REAL FUNCTION F3G (X)
C***BEGIN PROLOGUE  F3G
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F3G
      REAL X
C***FIRST EXECUTABLE STATEMENT  F3G
      F3G = ABS(X-0.33E+00)**(-0.9E+00)
      RETURN
      END
