*DECK F3S
      REAL FUNCTION F3S (X)
C***BEGIN PROLOGUE  F3S
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F3S
      REAL X
C***FIRST EXECUTABLE STATEMENT  F3S
      F3S = 0.1E+01
      IF(X.GT.3.1415926535897932) F3S = 0.0
      RETURN
      END
