*DECK F5S
      REAL FUNCTION F5S (X)
C***BEGIN PROLOGUE  F5S
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  F5S
      REAL X
C***FIRST EXECUTABLE STATEMENT  F5S
      F5S = 0.0
      IF(X.NE.0.0) F5S = 1.0/(X*SQRT(X))
      RETURN
      END
