!DECK FEIN
REAL FUNCTION FEIN(T)
  IMPLICIT NONE
  !***BEGIN PROLOGUE  FEIN
  !***PURPOSE  Subsidiary to EG8CK.
  !***LIBRARY   SLATEC
  !***AUTHOR  (UNKNOWN)
  !***ROUTINES CALLED  (NONE)
  !***COMMON BLOCKS    FEINX
  !***REVISION HISTORY  (YYMMDD)
  !   ??????  DATE WRITTEN
  !   891214  Prologue converted to Version 4.0 format.  (BAB)
  !***END PROLOGUE  FEIN
  COMMON /FEINX / X, A, FKM
  REAL X, A, FKM, T, aln
  !***FIRST EXECUTABLE STATEMENT  FEIN
  aln = (FKM-T)*X - A*LOG(T)
  FEIN = EXP(aln)
END FUNCTION FEIN
