*DECK FEIN
      REAL FUNCTION FEIN (T)
C***BEGIN PROLOGUE  FEIN
C***PURPOSE  Subsidiary to EG8CK.
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***COMMON BLOCKS    FEINX
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  FEIN
      COMMON /FEINX/ X, A, FKM
      REAL X, A, FKM, T, ALN
C***FIRST EXECUTABLE STATEMENT  FEIN
      ALN = (FKM-T)*X - A*LOG(T)
      FEIN = EXP(ALN)
      RETURN
      END
