*DECK SDRES1
      SUBROUTINE SDRES1 (T, Y, YPRIME, DELTA, IRES, RPAR, IPAR)
C***BEGIN PROLOGUE  SDRES1
C***SUBSIDIARY
C***PURPOSE  First residual evaluator for SDASQC.
C***LIBRARY   SLATEC (DASSL)
C***TYPE      SINGLE PRECISION (SDRES1-S, DDRES1-D)
C***AUTHOR  PETZOLD, LINDA R., (LLNL)
C***SEE ALSO  SDASQC
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   891013  DATE WRITTEN
C   901001  Converted prologue to 4.0 format and made all argument
C           declarations explicit.  (FNF)
C***END PROLOGUE  SDRES1
      INTEGER  IRES, IPAR(*)
      REAL  T, Y(*), YPRIME(*), DELTA(*), RPAR(*)
C***FIRST EXECUTABLE STATEMENT  SDRES1
      DELTA(1) = YPRIME(1) + 10.0E0*Y(1)
      DELTA(2) = Y(2) + Y(1) - 1.0E0
      RETURN
      END
