*DECK SOSFNC
      REAL FUNCTION SOSFNC (X, K)
C***BEGIN PROLOGUE  SOSFNC
C***PURPOSE  Function evaluator for SOS quick check.
C***LIBRARY   SLATEC
C***KEYWORDS  QUICK CHECK
C***AUTHOR  Watts, H. A., (SNLA)
C***DESCRIPTION
C
C     FUNCTION WHICH EVALUATES THE FUNCTIONS, ONE AT A TIME,
C     FOR TEST PROGRAM USED IN QUICK CHECK OF SOS.
C
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   801001  DATE WRITTEN
C   890618  REVISION DATE from Version 3.2
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  SOSFNC
      DIMENSION X(2)
C***FIRST EXECUTABLE STATEMENT  SOSFNC
      IF (K.EQ.1) SOSFNC=1.E0-X(1)
      IF (K.EQ.2) SOSFNC=1.E1*(X(2)-X(1)**2)
      RETURN
      END
