*DECK SQJAC2
      SUBROUTINE SQJAC2 (N, X, FVEC, FJAC, LDFJAC, IFLAG)
C***BEGIN PROLOGUE  SQJAC2
C***PURPOSE  Evaluate full Jacobian for SNSQE test.
C***LIBRARY   SLATEC
C***KEYWORDS  QUICK CHECK
C***AUTHOR  (UNKNOWN)
C***DESCRIPTION
C
C     SUBROUTINE TO EVALUATE THE FULL JACOBIAN FOR TEST PROBLEM USED
C     IN QUICK CHECK OF SNSQE.
C
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   890831  Modified array declarations.  (WRB)
C   890831  REVISION DATE from Version 3.2
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  SQJAC2
      DIMENSION X(*),FVEC(*),FJAC(LDFJAC,*)
C***FIRST EXECUTABLE STATEMENT  SQJAC2
      FJAC(1,1)=-1.E0
      FJAC(1,2)=0.E0
      FJAC(2,1)=-2.E1*X(1)
      FJAC(2,2)=1.E1
      RETURN
      END
