MODULE fishfft
  IMPLICIT NONE

CONTAINS
  INCLUDE'../fishfft/blktri.f90'
  INCLUDE'../fishfft/cblktr.f90'
!  INCLUDE'../fishfft/cfftb.f90'
  INCLUDE'../fishfft/cfftb1.f90'
!  INCLUDE'../fishfft/cfftf.f90'
  INCLUDE'../fishfft/cfftf1.f90'
!  INCLUDE'../fishfft/cffti.f90'
  INCLUDE'../fishfft/cffti1.f90'
  INCLUDE'../fishfft/cmgnbn.f90'
  INCLUDE'../fishfft/cosqb.f90'
  INCLUDE'../fishfft/cosqb1.f90'
  INCLUDE'../fishfft/cosqf.f90'
  INCLUDE'../fishfft/cosqf1.f90'
  INCLUDE'../fishfft/cosqi.f90'
  INCLUDE'../fishfft/cost.f90'
  INCLUDE'../fishfft/costi.f90'
  INCLUDE'../fishfft/ezfft1.f90'
  INCLUDE'../fishfft/ezfftb.f90'
  INCLUDE'../fishfft/ezfftf.f90'
!  INCLUDE'../fishfft/ezffti.f90'
  INCLUDE'../fishfft/genbun.f90'
  INCLUDE'../fishfft/hstcrt.f90'
  INCLUDE'../fishfft/hstcsp.f90'
  INCLUDE'../fishfft/hstcyl.f90'
  INCLUDE'../fishfft/hstplr.f90'
  INCLUDE'../fishfft/hstssp.f90'
  INCLUDE'../fishfft/hw3crt.f90'
  INCLUDE'../fishfft/hwscrt.f90'
  INCLUDE'../fishfft/hwscsp.f90'
  INCLUDE'../fishfft/hwscyl.f90'
  INCLUDE'../fishfft/hwsplr.f90'
  INCLUDE'../fishfft/hwsssp.f90'
  INCLUDE'../fishfft/passb.f90'
  INCLUDE'../fishfft/passb2.f90'
  INCLUDE'../fishfft/passb3.f90'
  INCLUDE'../fishfft/passb4.f90'
  INCLUDE'../fishfft/passb5.f90'
  INCLUDE'../fishfft/passf.f90'
  INCLUDE'../fishfft/passf2.f90'
  INCLUDE'../fishfft/passf3.f90'
  INCLUDE'../fishfft/passf4.f90'
  INCLUDE'../fishfft/passf5.f90'
  INCLUDE'../fishfft/pois3d.f90'
  INCLUDE'../fishfft/poistg.f90'
  INCLUDE'../fishfft/radb2.f90'
  INCLUDE'../fishfft/radb3.f90'
  INCLUDE'../fishfft/radb4.f90'
  INCLUDE'../fishfft/radb5.f90'
  INCLUDE'../fishfft/radbg.f90'
  INCLUDE'../fishfft/radf2.f90'
  INCLUDE'../fishfft/radf3.f90'
  INCLUDE'../fishfft/radf4.f90'
  INCLUDE'../fishfft/radf5.f90'
  INCLUDE'../fishfft/radfg.f90'
!  INCLUDE'../fishfft/rfftb.f90'
  INCLUDE'../fishfft/rfftb1.f90'
!  INCLUDE'../fishfft/rfftf.f90'
  INCLUDE'../fishfft/rfftf1.f90'
!  INCLUDE'../fishfft/rffti.f90'
  INCLUDE'../fishfft/rffti1.f90'
  INCLUDE'../fishfft/sepeli.f90'
  INCLUDE'../fishfft/sepx4.f90'
  INCLUDE'../fishfft/sinqb.f90'
  INCLUDE'../fishfft/sinqf.f90'
  INCLUDE'../fishfft/sinqi.f90'
  INCLUDE'../fishfft/sint.f90'
  INCLUDE'../fishfft/sinti.f90'
END MODULE fishfft
