MODULE pchip
  IMPLICIT NONE

CONTAINS
  INCLUDE'../pchip/chfcm.f90'
  INCLUDE'../pchip/chfdv.f90'
  INCLUDE'../pchip/chfev.f90'
  INCLUDE'../pchip/chfie.f90'
  INCLUDE'../pchip/dchfcm.f90'
  INCLUDE'../pchip/dchfdv.f90'
  INCLUDE'../pchip/dchfev.f90'
  INCLUDE'../pchip/dchfie.f90'
  INCLUDE'../pchip/dpchbs.f90'
  INCLUDE'../pchip/dpchce.f90'
  INCLUDE'../pchip/dpchci.f90'
  INCLUDE'../pchip/dpchcm.f90'
  INCLUDE'../pchip/dpchcs.f90'
  INCLUDE'../pchip/dpchdf.f90'
  INCLUDE'../pchip/dpchfd.f90'
  INCLUDE'../pchip/dpchfe.f90'
  INCLUDE'../pchip/dpchia.f90'
  INCLUDE'../pchip/dpchic.f90'
  INCLUDE'../pchip/dpchid.f90'
  INCLUDE'../pchip/dpchim.f90'
  INCLUDE'../pchip/dpchkt.f90'
  INCLUDE'../pchip/dpchsp.f90'
  INCLUDE'../pchip/dpchst.f90'
  INCLUDE'../pchip/dpchsw.f90'
  INCLUDE'../pchip/pchbs.f90'
  INCLUDE'../pchip/pchce.f90'
  INCLUDE'../pchip/pchci.f90'
  INCLUDE'../pchip/pchcm.f90'
  INCLUDE'../pchip/pchcs.f90'
  INCLUDE'../pchip/pchdf.f90'
  INCLUDE'../pchip/pchdoc.f90'
  INCLUDE'../pchip/pchfd.f90'
  INCLUDE'../pchip/pchfe.f90'
  INCLUDE'../pchip/pchia.f90'
  INCLUDE'../pchip/pchic.f90'
  INCLUDE'../pchip/pchid.f90'
  INCLUDE'../pchip/pchim.f90'
  INCLUDE'../pchip/pchkt.f90'
  INCLUDE'../pchip/pchsp.f90'
  INCLUDE'../pchip/pchst.f90'
  INCLUDE'../pchip/pchsw.f90'
END MODULE  pchip
