*DECK DGVEC
      SUBROUTINE DGVEC (X, G)
C***BEGIN PROLOGUE  DGVEC
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  DGVEC
      DOUBLE PRECISION X,G
      DIMENSION G(*)
C***FIRST EXECUTABLE STATEMENT  DGVEC
      G(1) = 0.0D0
      G(2) = 1.0D0+COS(X)
      RETURN
      END
