*DECK FMAT
      SUBROUTINE FMAT (X, Y, YP)
C***BEGIN PROLOGUE  FMAT
C***PURPOSE  Subsidiary to
C***LIBRARY   SLATEC
C***AUTHOR  (UNKNOWN)
C***ROUTINES CALLED  (NONE)
C***COMMON BLOCKS    SAVEX
C***REVISION HISTORY  (YYMMDD)
C   ??????  DATE WRITTEN
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C***END PROLOGUE  FMAT
      DIMENSION Y(*),YP(*)
      COMMON /SAVEX/ XSAVE, TERM
C***FIRST EXECUTABLE STATEMENT  FMAT
      YP(1) = Y(2)
      IF (X .EQ. XSAVE) GO TO 10
      XSAVE=X
      TANX=TAN(X/57.2957795130823)
      TERM=3.0/TANX+2.0*TANX
   10 YP(2) = -TERM*Y(2)-0.7*Y(1)
      RETURN
      END
